In [93]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score,precision_score, recall_score, f1_score

In [94]:
hep=pd.read_csv('hepatsis.csv')
hept=hep.copy()
hep.head()

,CLASS,AGE,SEX,STERIOD,ANTIVIRALS,FATIGUE,MALASIE,ANOREXIA,LIVER-BIG,LIVER-FIRM,SPLEEN-PALPABLE,SPIDERS,ASCITIES,VARICES,BILIRUBIN,ALK-PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1,85,18,4,?,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.9,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.7,96,32,4,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.7,46,52,4,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1,?,200,4,?,1

In [95]:
hep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CLASS            155 non-null    int64
 1   AGE              155 non-null    int64
 2   SEX              155 non-null    int64
 3   STERIOD          155 non-null    object
 4   ANTIVIRALS       155 non-null    int64
 5   FATIGUE          155 non-null    object
 6   MALASIE          155 non-null    object
 7   ANOREXIA         155 non-null    object
 8   LIVER-BIG        155 non-null    object
 9   LIVER-FIRM       155 non-null    object
 10  SPLEEN-PALPABLE  155 non-null    object
 11  SPIDERS          155 non-null    object
 12  ASCITIES         155 non-null    object
 13  VARICES          155 non-null    object
 14  BILIRUBIN        155 non-null    object
 15  ALK-PHOSPHATE    155 non-null    object
 16  SGOT             155 non-null    object
 17  ALBUMIN          155 non-null    object
 18  PROTIME          155 non-null    object
 19  HISTOLOGY        155 non-null    int64
dtypes: int64(5), object(15)
memory usage: 15.2+ KB

In [96]:
hep.replace('?',np.NaN,inplace=True)

In [97]:
hep.head()

,CLASS,AGE,SEX,STERIOD,ANTIVIRALS,FATIGUE,MALASIE,ANOREXIA,LIVER-BIG,LIVER-FIRM,SPLEEN-PALPABLE,SPIDERS,ASCITIES,VARICES,BILIRUBIN,ALK-PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1,85,18,4,NaN,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.9,135,42,3.5,NaN,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.7,96,32,4,NaN,1
3,2,31,1,NaN,1,2,2,2,2,2,2,2,2,2,0.7,46,52,4,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1,NaN,200,4,NaN,1

**Dealing with missing values using Backward fill**

In [98]:
hep1=hep.fillna(method='bfill')
hep1=hep1.astype(str).astype(float)
hep1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CLASS            155 non-null    float64
 1   AGE              155 non-null    float64
 2   SEX              155 non-null    float64
 3   STERIOD          155 non-null    float64
 4   ANTIVIRALS       155 non-null    float64
 5   FATIGUE          155 non-null    float64
 6   MALASIE          155 non-null    float64
 7   ANOREXIA         155 non-null    float64
 8   LIVER-BIG        155 non-null    float64
 9   LIVER-FIRM       155 non-null    float64
 10  SPLEEN-PALPABLE  155 non-null    float64
 11  SPIDERS          155 non-null    float64
 12  ASCITIES         155 non-null    float64
 13  VARICES          155 non-null    float64
 14  BILIRUBIN        155 non-null    float64
 15  ALK-PHOSPHATE    155 non-null    float64
 16  SGOT             155 non-null    float64
 17  ALBUMIN          155 non-null    float64
 18  PROTIME          155 non-null    float64
 19  HISTOLOGY        155 non-null    float64
dtypes: float64(20)
memory usage: 24.3 KB

In [99]:
hep1.head()

,CLASS,AGE,SEX,STERIOD,ANTIVIRALS,FATIGUE,MALASIE,ANOREXIA,LIVER-BIG,LIVER-FIRM,SPLEEN-PALPABLE,SPIDERS,ASCITIES,VARICES,BILIRUBIN,ALK-PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2.0,30.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,85.0,18.0,4.0,80.0,1.0
1,2.0,50.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,0.9,135.0,42.0,3.5,80.0,1.0
2,2.0,78.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,96.0,32.0,4.0,80.0,1.0
3,2.0,31.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,46.0,52.0,4.0,80.0,1.0
4,2.0,34.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,95.0,200.0,4.0,75.0,1.0

In [100]:
scaler=MinMaxScaler()
X=hep1[['AGE','SEX','STERIOD','ANTIVIRALS','FATIGUE','MALASIE','ANOREXIA','LIVER-BIG', 
              'LIVER-FIRM','SPLEEN-PALPABLE','SPIDERS','ASCITIES','VARICES','BILIRUBIN',
              'ALK-PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY']]
y=hep1[['CLASS']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=0)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print('Training Set:',X_train.shape,y_train.shape)
print('Test Set:',X_test.shape,y_test.shape)

Training Set: (100, 19) (100, 1)
Test Set: (55, 19) (55, 1)

In [101]:
random=RandomForestClassifier(criterion='gini',max_depth=100).fit(X_train_scaled,y_train)
Acc_ran=round(accuracy_score(y_test,random.predict(X_test_scaled)),3)
f1_ran=round(f1_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
recall_ran=round(recall_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
precision_ran=round(precision_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
print('Accuracy:',Acc_ran)
print('F1_Score:',f1_ran)
print('Recall_Score:',recall_ran)
print('Precision_Score:',precision_ran)

<ipython-input-101-29aa8bef4f25>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random=RandomForestClassifier(criterion='gini',max_depth=100).fit(X_train_scaled,y_train)

Accuracy: 0.855
F1_Score: 0.835
Recall_Score: 0.855
Precision_Score: 0.852

In [102]:
from sklearn.svm import SVC
svm=SVC(kernel='rbf',C=1000,gamma=0.01).fit(X_train_scaled,y_train)
Acc_svm=round(accuracy_score(y_test,svm.predict(X_test_scaled)),3)
f1_svm=round(f1_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
recall_svm=round(recall_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
precision_svm=round(precision_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
print('Accuracy:',Acc_svm)
print('F1_Score:',f1_svm)
print('Recall_Score:',recall_svm)
print('Precision_Score:',precision_svm)

Accuracy: 0.855
F1_Score: 0.843
Recall_Score: 0.855
Precision_Score: 0.846

c:\users\tejveer singh\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

**Filling using Forward Fill**

In [103]:
hep2=hep.fillna(method='ffill')
hep2=hep1.astype(str).astype(float)
hep2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CLASS            155 non-null    float64
 1   AGE              155 non-null    float64
 2   SEX              155 non-null    float64
 3   STERIOD          155 non-null    float64
 4   ANTIVIRALS       155 non-null    float64
 5   FATIGUE          155 non-null    float64
 6   MALASIE          155 non-null    float64
 7   ANOREXIA         155 non-null    float64
 8   LIVER-BIG        155 non-null    float64
 9   LIVER-FIRM       155 non-null    float64
 10  SPLEEN-PALPABLE  155 non-null    float64
 11  SPIDERS          155 non-null    float64
 12  ASCITIES         155 non-null    float64
 13  VARICES          155 non-null    float64
 14  BILIRUBIN        155 non-null    float64
 15  ALK-PHOSPHATE    155 non-null    float64
 16  SGOT             155 non-null    float64
 17  ALBUMIN          155 non-null    float64
 18  PROTIME          155 non-null    float64
 19  HISTOLOGY        155 non-null    float64
dtypes: float64(20)
memory usage: 24.3 KB

In [104]:
hep2.head()

,CLASS,AGE,SEX,STERIOD,ANTIVIRALS,FATIGUE,MALASIE,ANOREXIA,LIVER-BIG,LIVER-FIRM,SPLEEN-PALPABLE,SPIDERS,ASCITIES,VARICES,BILIRUBIN,ALK-PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2.0,30.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,85.0,18.0,4.0,80.0,1.0
1,2.0,50.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,0.9,135.0,42.0,3.5,80.0,1.0
2,2.0,78.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,96.0,32.0,4.0,80.0,1.0
3,2.0,31.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,46.0,52.0,4.0,80.0,1.0
4,2.0,34.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,95.0,200.0,4.0,75.0,1.0

In [105]:
scaler=MinMaxScaler()
X=hep2[['AGE','SEX','STERIOD','ANTIVIRALS','FATIGUE','MALASIE','ANOREXIA','LIVER-BIG', 
              'LIVER-FIRM','SPLEEN-PALPABLE','SPIDERS','ASCITIES','VARICES','BILIRUBIN',
              'ALK-PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY']]
y=hep2[['CLASS']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=0)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print('Training Set:',X_train.shape,y_train.shape)
print('Test Set:',X_test.shape,y_test.shape)

Training Set: (100, 19) (100, 1)
Test Set: (55, 19) (55, 1)

In [106]:
random=RandomForestClassifier().fit(X_train_scaled,y_train)
Acc_ran=round(accuracy_score(y_test,random.predict(X_test_scaled)),3)
f1_ran=round(f1_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
recall_ran=round(recall_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
precision_ran=round(precision_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
print('Accuracy:',Acc_ran)
print('F1_Score:',f1_ran)
print('Recall_Score:',recall_ran)
print('Precision_Score:',precision_ran)

<ipython-input-106-86aa08098825>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random=RandomForestClassifier().fit(X_train_scaled,y_train)

Accuracy: 0.836
F1_Score: 0.809
Recall_Score: 0.836
Precision_Score: 0.831

In [107]:
from sklearn.svm import SVC
svm=SVC(kernel='linear',C=1,gamma=1).fit(X_train_scaled,y_train)
Acc_svm=round(accuracy_score(y_test,svm.predict(X_test_scaled)),3)
f1_svm=round(f1_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
recall_svm=round(recall_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
precision_svm=round(precision_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
print('Accuracy:',Acc_svm)
print('F1_Score:',f1_svm)
print('Recall_Score:',recall_svm)
print('Precision_Score:',precision_svm)

Accuracy: 0.836
F1_Score: 0.819
Recall_Score: 0.836
Precision_Score: 0.824

c:\users\tejveer singh\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

**Using Iterative approach**

*Using Iterative Approach*

In [108]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp_mean = IterativeImputer(random_state=0)
imp_mean.fit(hep)

IterativeImputer(random_state=0)

In [109]:
# hep1=hep.copy()
hep3=imp_mean.transform(hep)

In [110]:
df=pd.DataFrame(hep3,columns=['CLASS','AGE','SEX','STERIOD','ANTIVIRALS','FATIGUE','MALASIE','ANOREXIA','LIVER-BIG', 
              'LIVER-FIRM','SPLEEN-PALPABLE','SPIDERS','ASCITIES','VARICES','BILIRUBIN',
              'ALK-PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY'])
df.head()

,CLASS,AGE,SEX,STERIOD,ANTIVIRALS,FATIGUE,MALASIE,ANOREXIA,LIVER-BIG,LIVER-FIRM,SPLEEN-PALPABLE,SPIDERS,ASCITIES,VARICES,BILIRUBIN,ALK-PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2.0,30.0,2.0,1.000000,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,85.000000,18.0,4.0,65.337287,1.0
1,2.0,50.0,1.0,1.000000,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,0.9,135.000000,42.0,3.5,61.471804,1.0
2,2.0,78.0,1.0,2.000000,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,96.000000,32.0,4.0,62.992618,1.0
3,2.0,31.0,1.0,1.539015,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,46.000000,52.0,4.0,80.000000,1.0
4,2.0,34.0,1.0,2.000000,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,122.369352,200.0,4.0,57.317882,1.0

In [111]:
scaler=MinMaxScaler()
X=df[['AGE','SEX','STERIOD','ANTIVIRALS','FATIGUE','MALASIE','ANOREXIA','LIVER-BIG', 
              'LIVER-FIRM','SPLEEN-PALPABLE','SPIDERS','ASCITIES','VARICES','BILIRUBIN',
              'ALK-PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY']]
y=df[['CLASS']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=0)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print('Training Set:',X_train.shape,y_train.shape)
print('Test Set:',X_test.shape,y_test.shape)
random=RandomForestClassifier(criterion='entropy',max_depth=5).fit(X_train_scaled,y_train)
Acc_ran=round(accuracy_score(y_test,random.predict(X_test_scaled)),3)
f1_ran=round(f1_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
recall_ran=round(recall_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
precision_ran=round(precision_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
print('Accuracy:',Acc_ran)
print('F1_Score:',f1_ran)
print('Recall_Score:',recall_ran)
print('Precision_Score:',precision_ran)

Training Set: (100, 19) (100, 1)
Test Set: (55, 19) (55, 1)

<ipython-input-111-a3b2d9d10fdb>:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random=RandomForestClassifier(criterion='entropy',max_depth=5).fit(X_train_scaled,y_train)

Accuracy: 0.855
F1_Score: 0.835
Recall_Score: 0.855
Precision_Score: 0.852

In [112]:
from sklearn.svm import SVC
svm=SVC(kernel='linear', gamma= 1, C= 1).fit(X_train_scaled,y_train)
Acc_svm=round(accuracy_score(y_test,svm.predict(X_test_scaled)),3)
f1_svm=round(f1_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
recall_svm=round(recall_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
precision_svm=round(precision_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
print('Accuracy:',Acc_svm)
print('F1_Score:',f1_svm)
print('Recall_Score:',recall_svm)
print('Precision_Score:',precision_svm)

Accuracy: 0.836
F1_Score: 0.827
Recall_Score: 0.836
Precision_Score: 0.825

c:\users\tejveer singh\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

*Using Simple Imputing approach*

In [113]:
hep1=hep.copy()
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="mean")
heps=(imp.fit_transform(hep))

In [114]:
heps1 = pd.DataFrame(heps, columns =['CLASS','AGE','SEX','STERIOD','ANTIVIRALS','FATIGUE','MALASIE','ANOREXIA','LIVER-BIG', 
              'LIVER-FIRM','SPLEEN-PALPABLE','SPIDERS','ASCITIES','VARICES','BILIRUBIN',
              'ALK-PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY'])
heps1.head()

,CLASS,AGE,SEX,STERIOD,ANTIVIRALS,FATIGUE,MALASIE,ANOREXIA,LIVER-BIG,LIVER-FIRM,SPLEEN-PALPABLE,SPIDERS,ASCITIES,VARICES,BILIRUBIN,ALK-PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2.0,30.0,2.0,1.000000,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,85.000000,18.0,4.0,61.852273,1.0
1,2.0,50.0,1.0,1.000000,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,0.9,135.000000,42.0,3.5,61.852273,1.0
2,2.0,78.0,1.0,2.000000,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,96.000000,32.0,4.0,61.852273,1.0
3,2.0,31.0,1.0,1.506494,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,46.000000,52.0,4.0,80.000000,1.0
4,2.0,34.0,1.0,2.000000,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,105.325397,200.0,4.0,61.852273,1.0

In [115]:
scaler=MinMaxScaler()
X=heps1[['AGE','SEX','STERIOD','ANTIVIRALS','FATIGUE','MALASIE','ANOREXIA','LIVER-BIG', 
              'LIVER-FIRM','SPLEEN-PALPABLE','SPIDERS','ASCITIES','VARICES','BILIRUBIN',
              'ALK-PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY']]
y=heps1[['CLASS']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=0)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print('Training Set:',X_train.shape,y_train.shape)
print('Test Set:',X_test.shape,y_test.shape)
random=RandomForestClassifier(criterion='gini',max_depth=100).fit(X_train_scaled,y_train)
Acc_ran=round(accuracy_score(y_test,random.predict(X_test_scaled)),3)
f1_ran=round(f1_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
recall_ran=round(recall_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
precision_ran=round(precision_score(y_test,random.predict(X_test_scaled),average='weighted'),3)
print('Accuracy:',Acc_ran)
print('F1_Score:',f1_ran)
print('Recall_Score:',recall_ran)
print('Precision_Score:',precision_ran)

Training Set: (100, 19) (100, 1)
Test Set: (55, 19) (55, 1)

<ipython-input-115-7cc9b09bbdbf>:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random=RandomForestClassifier(criterion='gini',max_depth=100).fit(X_train_scaled,y_train)

Accuracy: 0.891
F1_Score: 0.876
Recall_Score: 0.891
Precision_Score: 0.904

In [116]:
from sklearn.svm import SVC
svm=SVC().fit(X_train_scaled,y_train)
Acc_svm=round(accuracy_score(y_test,svm.predict(X_test_scaled)),3)
f1_svm=round(f1_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
recall_svm=round(recall_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
precision_svm=round(precision_score(y_test,svm.predict(X_test_scaled),average='weighted'),3)
print('Accuracy:',Acc_svm)
print('F1_Score:',f1_svm)
print('Recall_Score:',recall_svm)
print('Precision_Score:',precision_svm)

Accuracy: 0.836
F1_Score: 0.819
Recall_Score: 0.836
Precision_Score: 0.824

c:\users\tejveer singh\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)